### ISSUE TITLE
Global tracking of a gpu.

### ISSUE THREAD

**Issue by jdupl** [jdupl/StrangeLove#1]
We need a system to track a GPU with an ID. However, the cgminer API can only return a gpu id relative it's local machine.
Any ideas on how to link the two ?

Linking the machine id and card id would work, but if a card goes down (shutting down the machine and removing the card) the other GPU ids would probably not be the same.

The above method requires us to manually enter any changes in the relative id of the 

In this example we simulate gpu with s/n 1234 to fail at the pcie slot 0.

| (relative)Pcie slot | GPU relative id | serial number before failure | serial number after failure |
| --- | --- | --- | --- |
| 0 | GPU0 | 1234 | 123 |
| 1 | GPU1 | 123 | 12 |
| 2 | GPU2 | 12 | 1 |
| 3 | GPU3 | 1 | free |

The api can only (from my understanding) send the gpu id and not any real unique identifier.

We could leave the pcie slot free, but I believe the GPU id will skip free slots

**Comment by jdupl** [comment]
Simplest solution would be to physically identify each card with a global identifier and manually enter the corresponding relative id of cgminer to our global identifier. 
In the event of a card being removed or changed, the node's gpus ids need to be changed by a human.
Dealing with aticonfig and lspci will not give us satisfactory results to get a global id.

**Comment by fxleblanc** [comment]
A solution could be to post an issue in the principal repository of cgminer
and not the fork of ckolivas since this fork doesn't enable issues.

https://github.com/jgarzik/cpuminer

2014-01-29 Justin Duplessis notifications@github.com

**Comment by jdupl** [comment]
This is not cgMiner but a different miner for the CPU only. 
The problem lies for even the system to get a serial  number.
You better be forking the Linux kernel and AMD drivers =p
