### ISSUE TITLE
Get the ip from the server using the machines table

### ISSUE THREAD

**Issue by fxleblanc** [jdupl/StrangeLove#12]
### Add the ip adress column

When making a query to determine the right server to request, we need an ip column so the server id maps correctly to the right ip adress.
### New Method

When trying to request the server, a method with server_id parameter should be called in order to request the correct server. The return value will be the json response from the performance server.

**Comment by jdupl** [comment]
The "workflow" should look like a simple foreach

```
servers = db.getServers()
foreach(server as s)
    s.query()
```

Perhaps we should include an "active" property in the server table.
That way, we can disable queries to offline servers without deleting them.

```
servers = db.getServers()
foreach server as s
    if s.active
        s.query()
```

**Comment by fxleblanc** [comment]
### Refactoring

In addition, I propose we refactor all the database queries in a simple nodejs module aka database. Right now, if we choose this option, we will have three queries that will be refactored:
1. Server ip select to choose the right server
2. Insert the stats
3. Insert the server stats

**Comment by jdupl** [comment]
It's you module. Do what you think is both pleasing to the eyes and simple.
