### ISSUE TITLE
Framework to use for the webui

### ISSUE THREAD

**Issue by jdupl** [jdupl/StrangeLove#13]
Title says all.
I plan to use django. 
Who would be developping the webui ?

**Comment by sbstp** [comment]
I personally prefer bottle http://bottlepy.org/docs/dev/index.html and flask http://flask.pocoo.org/ as they are more lightweight than django.

**Comment by jdupl** [comment]
I would go for bottle.

Also, the web server hosting the site would need to be discussed.

I will put a VM online with Uwsgi to render the application.
Do we need an apache server on top of uwsgi ?

**Comment by sbstp** [comment]
We can use uwsgi or the builtin servers.
http://bottlepy.org/docs/0.12/deployment.html
It's a simple matter of installing it, such as `pip install cherrypy` and using it in the run function.
http://bottlepy.org/docs/0.12/api.html#bottle.run Here's the documentation for the run function. The reloader option is very useful. You will probably also have to hack jinja2 a bit to have it not cache the templates in development mode.

I also highly recommend using jinja2 (same syntax as twig and swig) for the templating engine. SimpleTemplate is too basic.
