### ISSUE TITLE
General columns

### ISSUE THREAD

**Issue by fxleblanc** [jdupl/StrangeLove#14]
Regarding the stats_machine table columns, from what I understand we need to have:
1. machine_id
2. uptime
3. load_avg

Do we need to include:
1. timestamp
2. server_id
3. request_status

Or do these columns go in the stats table?

**Comment by jdupl** [comment]
Of course we need timestamp.
Server_id and machine_id are the same.
Request status is only for the program to handle an error: request_status does not go in the database.
