### ISSUE TITLE
Cron task to make the http requests

### ISSUE THREAD

**Issue by fxleblanc** [jdupl/StrangeLove#15]
I propose node-schedule to make the cron tasks.

https://www.npmjs.org/package/node-schedule

**Comment by jdupl** [comment]
Wouldn't using a unix cron be simpler and more reliable ?
The main goal of the js module is to be both reliable and simple.

```
 */5 * * * * /home/strangelove/collect.js
```

**Comment by fxleblanc** [comment]
Since the node module will be a server, it would be much simpler to make a
js cron task embedded directly in the source code and perhaps if it's to
complicated, we could make a moduel that will create cron tasks based on a
.json configuration file.

2014-02-24 9:51 GMT-05:00 Justin Duplessis notifications@github.com:

**Comment by jdupl** [comment]
The module is not a server. It is a client as it only requests data from the miners which are the servers...
It will be unix crontab.
Stop trying to complicate the module o.O .

The module will be called each 5 minutes by cron and will request a status update for each server in the database's server table.

**Comment by fxleblanc** [comment]
No problem. Since you use cron outside of the application, all you will to do is make the command: 

```
node app.js
```
