### ISSUE TITLE
Map reducing performance inputs

### ISSUE THREAD

**Issue by fxleblanc** [jdupl/StrangeLove#3]
When we gather inputs from the performance input server, we will persists them in the table stats every 5 minutes using this format(with this example, I will not include the other columns for more clarity):

| timestamp | hashrate |
| --- | --- |
| 2014-02-13-05:30:30 | 50 |
| 2014-02-13-05:35:40 | 65 |
| 2014-02-13-05:40:40 | 34 |

Since there will be a big amount of data, we could map reduce it using this api:
https://npmjs.org/package/mapred
and use an average of the reduced records.

My question is where will we store the average data afterwards? Since the stats table receives the data from the 5min interval inputs, we could put the map reduced data in the same table but maybe it will conflict new inputs.

**Comment by jdupl** [comment]
Every X hours, we take the data from the "5min table" and for each card we calculate an average of the hashing power into another table.
We then clear the "5min table" and repeat the process.

| start | end | avg hashrate | gpu id |
| --- | --- | --- | --- |
| 2014-02-13-05:30:30 | 2014-02-13-05:40:40 | 49 | gpu id0 |

We will be able to get graph from this data

**Comment by fxleblanc** [comment]
These columns could be in a table named units_stats so we can persist the
average to calculate afterwards the share among users. So in conclusion,
there will be two tables where we store the performance inputs, the raw
stats in the stats table and the average data in the units_stats. If we
decide to go in this direction, we should modify the database structure.

2014-01-29 Justin Duplessis notifications@github.com

**Comment by jdupl** [comment]
There will be a single table containing all data of 5min intervals.
Data reduction will occur only after a long period of time. After 6 months lets say.
Keeping almost all data will not cost us too much performance and might be usefull someday.
With 10 devices to keep track of it's only around a million lines per year.
