### ISSUE TITLE
Algorithm charts 

### ISSUE THREAD

**Issue by jdupl** [jdupl/StrangeLove#6]
Algorithm to dynamically reduce data to dynamic periods. 
This will allow us the get data for a certain period of time and get a reasonable number of points to draw in the graph.
A month will contain 8640 records. A graph would need about 200 points at most.
This method will resemble 

```
array graphReduce(int numberOfPoints, array data)
```

**Comment by fxleblanc** [comment]
http://sigmajs.org/

**Comment by jdupl** [comment]
This is for graphs, not charts and does not parse the raw data.
